# Generated by Django 4.1.3 on 2022-11-08 02:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_id_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, editable=False, help_text='Geographic coordinates (lon/lat) as Point. Can be serialised from WKT (well-known text) representation', null=True, srid=4326, verbose_name='last location'),
        ),
    ]
