# Generated by Django 4.1.3 on 2022-11-08 02:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_location_profile_last_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
